// app/(platform)/residents/assignments/_components/mockData.ts
import { StudentAssignment, AvailableRoom } from './types';

export const pendingStudents: StudentAssignment[] = [
  {
    id: '1',
    name: 'Nguyễn Hải Anh',
    studentId: 'STU2024001',
    email: 'anh.nguyen@student.edu',
    phone: '0901 234 567',
    dateOfBirth: '2002-05-15',
    startYear: '2022',
    endYear: '2026',
    major: 'Computer Science',
    year: '3rd Year',
    faculty: 'Engineering',
    sleepTime: '23:00',
    wakeUpTime: '07:00',
    quietPreference: 'I need a very quiet room',
    socialPreference: 'I prefer limited interaction',
    studyHabit: 'I mostly study alone in silence',
    routineStrictness: 'I usually follow a fixed routine',
    adaptability: 'I can adapt to most roommates',
    preference: 'system',
    documents: { citizenId: true, studentCard: true },
    status: 'pending',
    createdAt: '2024-10-15',
  },
  {
    id: '2',
    name: 'Trần Minh Quân',
    studentId: 'STU2024002',
    email: 'quan.tran@student.edu',
    phone: '0902 345 678',
    dateOfBirth: '2001-08-20',
    startYear: '2022',
    endYear: '2026',
    major: 'Business Administration',
    year: '3rd Year',
    faculty: 'Business',
    sleepTime: '00:00',
    wakeUpTime: '08:00',
    quietPreference: 'Neutral',
    socialPreference: 'I like talking with roommates',
    studyHabit: 'Flexible / neutral',
    routineStrictness: 'My routine is somewhat flexible',
    adaptability: 'Neutral',
    preference: 'friend',
    friendName: 'Nguyễn Văn Bảo',
    friendId: 'STU2024005',
    friendBlock: 'A',
    friendFloor: '2',
    friendRoom: 'A201',
    documents: { citizenId: true, studentCard: false },
    status: 'pending',
    createdAt: '2024-10-18',
  },
  {
    id: '3',
    name: 'Phạm Thúc Linh',
    studentId: 'STU2024003',
    email: 'linh.pham@student.edu',
    phone: '0903 456 789',
    dateOfBirth: '2003-01-10',
    startYear: '2023',
    endYear: '2027',
    major: 'Engineering',
    year: '2nd Year',
    faculty: 'Engineering',
    sleepTime: '22:00',
    wakeUpTime: '06:00',
    quietPreference: 'I prefer a quiet room',
    socialPreference: 'I prefer limited interaction',
    studyHabit: 'I prefer quiet individual study',
    routineStrictness: 'I usually follow a fixed routine',
    adaptability: 'I need time to adapt',
    preference: 'system',
    documents: { citizenId: true, studentCard: true },
    status: 'pending',
    createdAt: '2024-10-16',
  },
  {
    id: '4',
    name: 'Lê Thị Yên',
    studentId: 'STU2024004',
    email: 'yen.le@student.edu',
    phone: '0904 567 890',
    dateOfBirth: '2002-11-25',
    startYear: '2021',
    endYear: '2025',
    major: 'Psychology',
    year: '4th Year',
    faculty: 'Social Sciences',
    sleepTime: '00:00',
    wakeUpTime: '09:00',
    quietPreference: 'Neutral',
    socialPreference: 'I enjoy a highly social room',
    studyHabit: 'Flexible / neutral',
    routineStrictness: 'My routine changes often',
    adaptability: 'I adapt very easily',
    preference: 'friend',
    friendName: 'Hoàng Văn Mạnh',
    friendId: 'STU2024006',
    friendBlock: 'B',
    friendFloor: '1',
    friendRoom: 'B101',
    documents: { citizenId: true, studentCard: true },
    status: 'pending',
    createdAt: '2024-10-14',
  },
  {
    id: '5',
    name: 'Hoàng Văn Mạnh',
    studentId: 'STU2024005',
    email: 'manh.hoang@student.edu',
    phone: '0905 678 901',
    dateOfBirth: '2002-09-08',
    startYear: '2022',
    endYear: '2026',
    major: 'Mathematics',
    year: '3rd Year',
    faculty: 'Science',
    sleepTime: '23:30',
    wakeUpTime: '07:30',
    quietPreference: 'I can tolerate normal room noise',
    socialPreference: 'Neutral',
    studyHabit: 'I sometimes study with others',
    routineStrictness: 'I usually follow a fixed routine',
    adaptability: 'I can adapt to most roommates',
    preference: 'friend',
    friendName: 'Lê Thị Yên',
    friendId: 'STU2024004',
    friendBlock: 'B',
    friendFloor: '1',
    friendRoom: 'B101',
    documents: { citizenId: false, studentCard: true },
    status: 'pending',
    createdAt: '2024-10-14',
  },
];

export const availableRooms: AvailableRoom[] = [
  { id: 'r1', block: 'A', blockId: 'block-a', floor: 2, roomNumber: 'A201', capacity: 4, currentOccupants: 2, availableSlots: 2 },
  { id: 'r2', block: 'A', blockId: 'block-a', floor: 2, roomNumber: 'A202', capacity: 4, currentOccupants: 1, availableSlots: 3 },
  { id: 'r3', block: 'A', blockId: 'block-a', floor: 3, roomNumber: 'A301', capacity: 4, currentOccupants: 3, availableSlots: 1 },
  { id: 'r4', block: 'B', blockId: 'block-b', floor: 1, roomNumber: 'B101', capacity: 4, currentOccupants: 2, availableSlots: 2 },
  { id: 'r5', block: 'B', blockId: 'block-b', floor: 1, roomNumber: 'B102', capacity: 4, currentOccupants: 0, availableSlots: 4 },
  { id: 'r6', block: 'B', blockId: 'block-b', floor: 2, roomNumber: 'B201', capacity: 4, currentOccupants: 1, availableSlots: 3 },
  { id: 'r7', block: 'C', blockId: 'block-c', floor: 3, roomNumber: 'C301', capacity: 4, currentOccupants: 2, availableSlots: 2 },
  { id: 'r8', block: 'C', blockId: 'block-c', floor: 3, roomNumber: 'C302', capacity: 4, currentOccupants: 3, availableSlots: 1 },
];

export const assignedStudents: StudentAssignment[] = [
  {
    id: '6',
    name: 'Võ Minh Khoa',
    studentId: 'STU2024006',
    email: 'khoa.vo@student.edu',
    phone: '0906 789 012',
    dateOfBirth: '2002-03-12',
    startYear: '2022',
    endYear: '2026',
    major: 'Physics',
    year: '3rd Year',
    faculty: 'Science',
    sleepTime: '22:30',
    wakeUpTime: '06:30',
    quietPreference: 'I prefer a quiet room',
    socialPreference: 'I prefer limited interaction',
    studyHabit: 'I prefer quiet individual study',
    routineStrictness: 'I usually follow a fixed routine',
    adaptability: 'I can adapt to most roommates',
    preference: 'system',
    documents: { citizenId: true, studentCard: true },
    status: 'assigned',
    assignedRoom: 'A201',
    assignedBlock: 'A',
    assignedFloor: 2,
    createdAt: '2024-10-12',
  },
  {
    id: '7',
    name: 'Ngô Thị Hương',
    studentId: 'STU2024007',
    email: 'huong.ngo@student.edu',
    phone: '0907 890 123',
    dateOfBirth: '2003-06-20',
    startYear: '2023',
    endYear: '2027',
    major: 'Biology',
    year: '2nd Year',
    faculty: 'Science',
    sleepTime: '23:00',
    wakeUpTime: '07:00',
    quietPreference: 'Neutral',
    socialPreference: 'I like talking with roommates',
    studyHabit: 'Flexible / neutral',
    routineStrictness: 'My routine is somewhat flexible',
    adaptability: 'Neutral',
    preference: 'system',
    documents: { citizenId: true, studentCard: true },
    status: 'assigned',
    assignedRoom: 'B101',
    assignedBlock: 'B',
    assignedFloor: 1,
    createdAt: '2024-10-13',
  },
];